version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: uselamor
      POSTGRES_PASSWORD: Password@123
      POSTGRES_DB: elamor_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: api_container
    depends_on:
      - db
    ports:
      - '3001:3001'
    environment:
      DATABASE_URL: postgres://uselamor:Password123@db:5432/elamor_db

volumes:
  postgres_data:
